const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
  personas: {
    getAll: () => ipcRenderer.invoke('personas:getAll'),
    create: (data) => ipcRenderer.invoke('personas:create', data),
    update: (id, data) => ipcRenderer.invoke('personas:update', { id, data }),
    delete: (id) => ipcRenderer.invoke('personas:delete', id),
  },
  edificios: {
    getAll: () => ipcRenderer.invoke('edificios:getAll'),
    create: (data) => ipcRenderer.invoke('edificios:create', data),
    update: (id, data) => ipcRenderer.invoke('edificios:update', { id, data }),
    delete: (id) => ipcRenderer.invoke('edificios:delete', id),
  },
  unidades: {
    getAll: () => ipcRenderer.invoke('unidades:getAll'),
    create: (data) => ipcRenderer.invoke('unidades:create', data),
    update: (id, data) => ipcRenderer.invoke('unidades:update', { id, data }),
    delete: (id) => ipcRenderer.invoke('unidades:delete', id),
  },
  contratos: {
    getAll: () => ipcRenderer.invoke('contratos:getAll'),
    getById: (id) => ipcRenderer.invoke('contratos:getById', id),
    create: (data, garantesIds) => ipcRenderer.invoke('contratos:create', { data, garantesIds }),
    update: (id, data, garantesIds) => ipcRenderer.invoke('contratos:update', { id, data, garantesIds }),
    delete: (id) => ipcRenderer.invoke('contratos:delete', id),
  },
  periodos: {
    getByContrato: (contratoId) => ipcRenderer.invoke('periodos:getByContrato', contratoId),
    update: (id, data) => ipcRenderer.invoke('periodos:update', { id, data }),
  },
  cuentas: {
    getAll: () => ipcRenderer.invoke('cuentas:getAll'),
    create: (data) => ipcRenderer.invoke('cuentas:create', data),
    update: (id, data) => ipcRenderer.invoke('cuentas:update', { id, data }),
    delete: (id) => ipcRenderer.invoke('cuentas:delete', id),
  },
  libroDiario: {
    getAll: () => ipcRenderer.invoke('libroDiario:getAll'),
  },
  cobros: {
    create: (data) => ipcRenderer.invoke('cobros:create', data),
    delete: (id, periodoId) => ipcRenderer.invoke('cobros:delete', { id, periodoId }),
  },
  tarjetas: {
    getAll: () => ipcRenderer.invoke('tarjetas:getAll'),
    create: (data) => ipcRenderer.invoke('tarjetas:create', data),
    update: (id, data) => ipcRenderer.invoke('tarjetas:update', { id, data }),
    delete: (id) => ipcRenderer.invoke('tarjetas:delete', id),
  },
  gastos: {
    getByTarjeta: (tarjetaId) => ipcRenderer.invoke('gastos:getByTarjeta', tarjetaId),
    create: (data, cuotasMonto) => ipcRenderer.invoke('gastos:create', { data, cuotasMonto }),
    delete: (id) => ipcRenderer.invoke('gastos:delete', id),
  },
  resumenes: {
    getByTarjeta: (tarjetaId) => ipcRenderer.invoke('resumenes:getByTarjeta', tarjetaId),
    create: (data) => ipcRenderer.invoke('resumenes:create', data),
    pagar: (id, cuentaId, fecha, monto, medio) => ipcRenderer.invoke('resumenes:pagar', { id, cuentaId, fecha, monto, medio }),
    delete: (id) => ipcRenderer.invoke('resumenes:delete', id),
  },
  servicios: {
    getAll: () => ipcRenderer.invoke('servicios:getAll'),
    create: (data) => ipcRenderer.invoke('servicios:create', data),
    update: (id, data) => ipcRenderer.invoke('servicios:update', { id, data }),
    delete: (id) => ipcRenderer.invoke('servicios:delete', id),
  },
  boletas: {
    getByServicio: (servicioId) => ipcRenderer.invoke('boletas:getByServicio', servicioId),
    create: (data) => ipcRenderer.invoke('boletas:create', data),
    update: (id, data) => ipcRenderer.invoke('boletas:update', { id, data }),
    delete: (id) => ipcRenderer.invoke('boletas:delete', id),
    pagar: (id, cuentaId, fecha, medio, responsable) => ipcRenderer.invoke('boletas:pagar', { id, cuentaId, fecha, medio, responsable }),
  },
  ivaCompras: {
    getAll: () => ipcRenderer.invoke('ivaCompras:getAll'),
    create: (data) => ipcRenderer.invoke('ivaCompras:create', data),
    update: (id, data) => ipcRenderer.invoke('ivaCompras:update', { id, data }),
    delete: (id) => ipcRenderer.invoke('ivaCompras:delete', id),
  },
  ivaVentas: {
    getAll: () => ipcRenderer.invoke('ivaVentas:getAll'),
    create: (data) => ipcRenderer.invoke('ivaVentas:create', data),
    update: (id, data) => ipcRenderer.invoke('ivaVentas:update', { id, data }),
    delete: (id) => ipcRenderer.invoke('ivaVentas:delete', id),
  },
  dashboard: {
    getMetrics: () => ipcRenderer.invoke('dashboard:getMetrics'),
  },
  catalogos: {
    tiposDocumento: () => ipcRenderer.invoke('catalogos:tiposDocumento'),
    tiposPersona: () => ipcRenderer.invoke('catalogos:tiposPersona'),
    rolesPersona: () => ipcRenderer.invoke('catalogos:rolesPersona'),
    estadosPersona: () => ipcRenderer.invoke('catalogos:estadosPersona'),
    tiposUnidad: () => ipcRenderer.invoke('catalogos:tiposUnidad'),
    perfilesCobro: () => ipcRenderer.invoke('catalogos:perfilesCobro'),
    estadosUnidad: () => ipcRenderer.invoke('catalogos:estadosUnidad'),
    estadosContrato: () => ipcRenderer.invoke('catalogos:estadosContrato'),
    tiposIndice: () => ipcRenderer.invoke('catalogos:tiposIndice'),
    periodicidades: () => ipcRenderer.invoke('catalogos:periodicidades'),
    imputaciones: () => ipcRenderer.invoke('catalogos:imputaciones'),
    tiposCuenta: () => ipcRenderer.invoke('catalogos:tiposCuenta'),
    monedas: () => ipcRenderer.invoke('catalogos:monedas'),
    mediosPago: () => ipcRenderer.invoke('catalogos:mediosPago'),
    tiposServicio: () => ipcRenderer.invoke('catalogos:tiposServicio'),
    estadosBoleta: () => ipcRenderer.invoke('catalogos:estadosBoleta'),
    responsablesPago: () => ipcRenderer.invoke('catalogos:responsablesPago'),
    marcasTarjeta: () => ipcRenderer.invoke('catalogos:marcasTarjeta'),
    estadosResumen: () => ipcRenderer.invoke('catalogos:estadosResumen'),
    tiposComprobante: () => ipcRenderer.invoke('catalogos:tiposComprobante'),
  },
})